### ISSUE TITLE
Add shutdown to System menu?

### ISSUE THREAD

**Issue by NelsonPJ** [mcuadros/OctoPrint-TFT#10]
I see that you have a "reboot" button in the System menu - can you also add a "shutdown" button?

I also don't think the "reboot" button does a reboot as cleanly as what's built into OctoPrint?  I think  both the reboot and shutdown buttons should look for commands defined in the "server:" portion of the config.yaml (as shown below) 

```
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now

```
